### ISSUE TITLE
Error changing edit targets

### ISSUE THREAD

**Issue by csaez** [LumaPictures/usd-qt#20]
Hi there,

Looks like the `dataChanged` signal fails to get emitted on PyQt5 (it work on PySide, PySide2 and PyQt4).

```python
Traceback (most recent call last):
  File "/home/users/cesars/packages/usd_qt/0.a.3/lib/python/pxr/UsdQtEditors/outliner.py", line 269, in ChangeEditTarget
    self._stage.SetEditTarget(newLayer)
  File "/home/users/cesars/packages/usd_qt/0.a.3/lib/python/pxr/UsdQtEditors/outliner.py", line 123, in _OnEditTargetChanged
    self.dataChanged[QtCore.QModelIndex, QtCore.QModelIndex].emit(
KeyError: 'there is no matching overloaded signal'
```

### Repro:
- Run the outliner
- Tools > Change Edit Target
- Double click on Kitchen_set.usd (or any non active layer)

Here's the code I'm using to run the outliner:

```python
import sys
from Qt import QtWidgets
from pxr.UsdQtEditors import outliner

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    filepath = './usd_kitchen/Kitchen_set.usd'
    d = outliner.UsdOutlinerDialog.FromUsdFile(filepath)
    d.show()
    sys.exit(app.exec_())
```

### Environment:
- PyQt-5.9.0.1
- Qt_vfx-5.6.1.7.0
- Qtpy-1.1.0

**Comment by nrusch** [comment]
Fixed by #21
