### ISSUE TITLE
usd-qt outliner dialog crashing on show()

### ISSUE THREAD

**Issue by DanEnglesson** [LumaPictures/usd-qt#22]
Hi,
I'm building the usd-qt code after seeing it being used at Siggraph this year with AL_USDMaya and it looks really useful!

I'm using cmake version 3.12.1 to build it and I figured I should use the same boost as what the core USD has been built with, in this case boost 1.55, like this:

    cmake3  \
    -DCMAKE_INSTALL_PREFIX='/usr/local/USD.18.09/USD_QT'  \
    -DBOOST_INCLUDEDIR=/usr/local/USD.18.09/USD-core/include\
    /mnt/home/dan.englesson/USD/usd-qt
    make -j12 install

It builds and installs just fine. Output from build:

     CMake Warning (dev) at CMakeLists.txt:23 (find_package):
     Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
     Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
     command to set the policy and suppress this warning.

     Environment variable USD_ROOT is set to:

       /usr/local/USD.18.09/USD-core

     For compatibility, CMake is ignoring the variable.
     This warning is for project developers.  Use -Wno-dev to suppress it.

     -- Boost version: 1.55.0
     -- Found the following Boost libraries:
     --   python
     -- Configuring done
     -- Generating done
     -- Build files have been written to: /mnt/home/dan.englesson/USD/usd-qt_new/build

This installs fine, and most of it seems to work. Opening up Maya2018 with my installpath added to the PYTHONPATH environment variable and everything seems to work fine, until I do dialog.show().
```
def GetStage():
    from AL import usdmaya
    stageCache = usdmaya.StageCache.Get()
    stages = stageCache.GetAllStages()
    if stages:
        return stages[0]
    else:
        raise RuntimeError('No stage loaded in AL_USDMaya!')
        
def OpenOutliner():
    from pxr.UsdQtEditors.outliner import UsdOutliner
    stage = GetStage()
    dialog = UsdOutliner(stage)
    dialog.show() <----------------------------------------------------- segfault
    return dialog

dlg = OpenOutliner()
```

Attaching the maya crash-log, and I think it's boost related. 
[crashLog.txt](https://github.com/LumaPictures/usd-qt/files/2463627/crashLog.txt)
`_ZN5boost4asio6detail15task_io_service3runERNS_6system10error_codeE`

If I lock it with dialog.exec_() just after dialog.show() I don't get it to crash, which point to some threading issue. However, with this working the updates only shows up if I click in the maya viewport after each change and it doesn't seem to sync with the selection in the viewport.
I'm just curious to hear how you compiled it. When I compile it with boost 1.61 which is the boost for maya2018 I get some weird issues with not finding __MFB_FULL_PACKAGE_NAME
```
# Error: 'NoneType' object has no attribute '__MFB_FULL_PACKAGE_NAME'
# Traceback (most recent call last):
#   File "<maya console>", line 18, in <module>
#   File "<maya console>", line 11, in OpenOutliner
#   File "/usr/local/USD.18.09/USD_QT/lib/python/pxr/UsdQtEditors/outliner.py", line 36, in <module>
#     from pxr.UsdQt.hierarchyModel import HierarchyBaseModel
#   File "/usr/local/USD.18.09/USD_QT/lib/python/pxr/UsdQt/hierarchyModel.py", line 30, in <module>
#     from ._bindings import PrimFilterCache, _HierarchyCache
#   File "/usr/local/USD.18.09/USD_QT/lib/python/pxr/UsdQt/_bindings.py", line 25, in <module>
#     import pxr.UsdQt._usdQt as _usdQt
# AttributeError: 'NoneType' object has no attribute '__MFB_FULL_PACKAGE_NAME' # 
```

Any help would be much appreciated.
Thanks,
Dan

**Comment by bfloch** [comment]
That's exactly the crash that we are seeing.
I recognize the following symbol in @DanEnglesson crashlog:
`QItemSelectionModel::isSelected(QModelIndex const&) const  `

I've stepped through with a python debugger and was able to isolate it happening here:
https://github.com/LumaPictures/usd-qt/blob/master/pxr/usdQt/hierarchyModel.py#L247

The root variable seems to be a valid python object at this point, which is a wrapped Usd object I believe. My understanding is that the Qt API at this point accepts a void pointer while PySide should allow the object to be stored.
So maybe it is the boost wrapper causing problems here as Dan suggests. Ideas?

**Comment by nrusch** [comment]
Hi @DanEnglesson,

My immediate suspicion here is that this may be related to the fact that there are two different versions of Boost at play here. Is there any chance you can try building both USD and usd-qt against Boost 1.61? This combination is working well for us internally (in and out of Maya).

**Comment by csaez** [comment]
The intended usage requires more than just passing the stage in memory:
https://github.com/LumaPictures/usd-qt/blob/master/pxr/usdQtEditors/outliner.py#L911

You can try passing the same filepath set in the AL_USDMaya proxy shape to `FromUsdFile` (AL_USDMaya populate UsdStageCache, so Usd will reuse the same instance).

**Comment by DanEnglesson** [comment]
Hi csaez, thanks for your suggestion.
I've tried it out and it still fails. Just loading it directly with FromUsdFile fails as well, which might be easier to debug as well:

```
def OpenOutliner():
    from pxr.UsdQtEditors.outliner import UsdOutliner
    dialog = UsdOutliner.FromUsdFile('/mnt/home/dan.englesson/USD/kitchen_scene/Kitchen_set.usd')
    dialog.show()
    dialog.raise_()
    dialog.activateWindow()
    return dialog


dlg = OpenOutliner()
```

Thanks,
Dan

**Comment by nrusch** [comment]
Hi @DanEnglesson @bfloch,

Sorry for the confusion here. Your mention of `QItemSelectionModel::isSelected` reminded me that @nxkb recently fixed a crash related to the outliner's item selection model, and the changes are currently on the dev branch (which is the basis of what we use internally).

Can you give this one more try from the tip of dev? Assuming it works, it's probably worth merging dev into master shortly, since this is a bit of a showstopper.

Thanks.

**Comment by DanEnglesson** [comment]
Yay the dev-branch worked! I was able to do dialog.show() without the crash.

![image](https://user-images.githubusercontent.com/454591/46855577-6ab15e00-ce04-11e8-819c-1ba18f4b7f91.png)

```
def GetStage():
    from AL import usdmaya
    stageCache = usdmaya.StageCache.Get()
    stages = stageCache.GetAllStages()
    if stages:
        return stages[0]
    else:
        raise RuntimeError('No stage loaded in AL_USDMaya!')
        
def OpenOutliner():
    from pxr.UsdQtEditors.outliner import UsdOutlinerDialog
    stage = GetStage()
    dialog = UsdOutlinerDialog(stage)
    dialog.show()
    return dialog


dlg = OpenOutliner()
```
So to conclude, this bug seems to have been resolved in your dev branch.

However, there still seem to be some viewer update issues with changing variants and activating/deactivating objects. If I deactivate the table, it wont update in the viewer unless I move around a bit. Same with switching variant on the table chairs. Have you guys experienced that?
Maybe I opened it in a weird way, see code above, but it seems like the header is incorrect as well. Just want to make sure I'm doing this correctly.

Many thanks for the help resolving this!
Dan

**Comment by DanEnglesson** [comment]
Sounds good, thanks for all the help on this.
cheers,
Dan

**Comment by DanEnglesson** [comment]
Thanks for the info @nxkb that's good to know!

Thanks,
Dan
